### PR TITLE
Fix HTTP connection leak on Datastore errors

### LINKED ISSUE #185: RemoteRpc leaks HTTP connections when handling Datastore errors
The exception handling code in `com.google.datastore.v1.client.RemoteRpc` does not close the HTTP content input stream after parsing the protobuf message `com.google.rpc.Status` (which describes the Datastore error).

Closing the content input stream allows the underlying `HttpTransport` to clean up resources (i.e. release the leased HTTP connection back to the connection pool). Without cleanup, alternative `HttpTransport` implementations (e.g. `ApacheHttpTransport`) experience connection timeouts as soon as they have depleted their connection pool.

### PR DESCRIPTION
**Pull request by cmaan**
Properly close HTTP response input stream on Datastore errors (fixes #185)

### CODE REVIEW

File: java/datastore/src/main/java/com/google/datastore/v1/client/RemoteRpc.java [hunk 1]
```diff
@@ -249,6 +249,12 @@ static DatastoreException makeException(String url, String methodName, InputStre
           String.format(
               "Unable to parse Status protocol buffer: HTTP status code was %s.", httpStatusCode),
           e);
+    } finally {
+      try {
+        content.close();
+      } catch(IOException e) {
+        logger.fine(String.format("closing content stream failed: %s",e));
+      }
```
Comment (eddavisson) [inline java/datastore/src/main/java/com/google/datastore/v1/client/RemoteRpc.java]: I think we can also fail to close the stream in the try block that starts at line 231. What about instead adding a try-finally around the code at line 185. That should ensure the stream is closed no matter what happens in this method.

Comment (cmaan) [reply java/datastore/src/main/java/com/google/datastore/v1/client/RemoteRpc.java]: I updated the pull request based on your suggestion, and also modified the `IOUtils.copy` line to avoid a potential double-close.

File: java/datastore/src/main/java/com/google/datastore/v1/client/RemoteRpc.java [hunk 2]
```diff
@@ -182,9 +182,11 @@ public InputStream call(String methodName, MessageLite request) throws Datastore
         }
         httpResponse = httpRequest.execute();
         if (!httpResponse.isSuccessStatusCode()) {
-          throw makeException(url, methodName, httpResponse.getContent(),
-              httpResponse.getContentType(), httpResponse.getContentCharset(), null,
-              httpResponse.getStatusCode());
+          try(InputStream content = httpResponse.getContent()) {
```
Comment (eddavisson) [inline java/datastore/src/main/java/com/google/datastore/v1/client/RemoteRpc.java]: Add a blank space after try.

Comment (cmaan) [reply java/datastore/src/main/java/com/google/datastore/v1/client/RemoteRpc.java]: done!

**Comment by danieln100** [comment]
Will this fix be included in the next release? We are seeing some consistent spikes in latency numbers and of our theories is that the Http connection pool is getting exhausted somehow, so I am very interested in trying this.

**Comment by wsh** [comment]
@danieln100 we hear you. We've released v1.5.1, which includes this fix. Give it a spin and let us know!

**Comment by danieln100** [comment]
@wsh Awesome thanks. I deleted my question before you answered me because I wanted to move it to a separate issue but just for context I asked how would I able to use this change since we are experiencing consistent spikes in latency and we think its due to a http connection leak. 

What is the best way to use this with the Google Cloud Java Client for Datastore, I am using version 1.8 and looking at the pom.xml file for that version it looks like they are still using `1.3.0`. Would just adding this project as a dependency to my project after the dependency for the java client work (I am using SBT)? 

Thanks again

**Comment by wsh** [comment]
@danieln100 google-cloud-java/google-cloud-datastore 1.8.0 [uses version 1.4.1](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/73a9e10ef3bf5dda09d4bdb06a1f9f15ccf9e0ff/google-cloud-datastore/pom.xml#L38) of this library. (Seems like you're looking at the proto dependencies.) At least in theory, specifying 1.5.1 might work but, now that [this pull request](https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2574) has been merged, 1.5.1 will also be included in the next release of google-cloud-java. Your call. :smile:
